name: Snake Game

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"
  push:
    paths:
      - ".github/workflows/**"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Gerar SVG da cobrinha
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publicar SVG no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
